---

# create data manager config
- name: Set galaxy_config to impersonate_config_hash
  set_fact:
    galaxy_config: "{{ impersonate_config_hash }}"

- name: Create Galaxy data manager configuration file
  template:
    src: templates/galaxy/config/galaxy.ini.j2
    dest: "{{ galaxy_config_dir }}/impersonate.ini"
    backup: yes
