---

# Tool Shed version
galaxy_commit_id: b9fb2de42b53fcb1516422cdd3d40177d507529a


group_crontabs:
  - id: test_shed_backup
    name: Test Toolshed Backup
    user: shed
    hour: 23
    minute: 0
    job: rsync -av --delete /srv/toolshed/test/var /srv/toolshed/test/log zfsdump-radegast@westvleteren.galaxyproject.org:/zones/westvleteren/backup/radegast/testshed && ssh -T zfsdump-radegast@westvleteren.galaxyproject.org -- /usr/sbin/zfs snapshot zones/westvleteren/backup/radegast/testshed@`date -u +\%Y\%m\%dT\%H\%M\%SZ`


## these vars are defined in vault.yml
#
# used by: galaxy_toolshed_config var
galaxy_toolshed_config_admin_users: "{{ vault_galaxy_toolshed_config_admin_users }}"
galaxy_toolshed_config_id_secret: "{{ vault_galaxy_toolshed_config_id_secret }}"
galaxy_toolshed_config_sentry_dsn: "{{ vault_galaxy_toolshed_config_sentry_dsn }}"


## used by: other vars in this vars file
galaxy_toolshed_root: "/srv/toolshed/{{ galaxy_toolshed_instance_codename }}"
galaxy_toolshed_server_dir: "{{ galaxy_toolshed_root }}/server"
galaxy_toolshed_log_dir: "{{ galaxy_toolshed_root }}/log"


## used by: galaxyproject.galaxy and usegalaxy_admin, the update play
toolshed_user: shed
toolshed_privileged_user: gxsrc
galaxy_user: "{{ toolshed_user }}"
galaxy_privileged_user: "{{ toolshed_privileged_user }}"
# the only thing this is used for is setting the group on the errordocs destination directory
galaxy_system_group: gxsrc


## used by: supervisor
galaxy_toolshed_instance_codename: test
supervisord_group_configs:
  - testtoolshed


galaxy_toolshed_instance_hostname: testtoolshed.g2.bx.psu.edu


## used by: natefoo.postgresql_objects
postgresql_objects_databases:
  - name: galaxy_testtoolshed
    owner: shed

postgresql_objects_privileges:
  - database: galaxy_testtoolshed
    objs: ALL_IN_SCHEMA
    roles: galaxy_team
    privs: SELECT
  - database: galaxy_testtoolshed
    objs: ALL_IN_SCHEMA
    roles: shed
    privs: ALL
  - database: galaxy_testtoolshed
    objs: ALL_IN_SCHEMA
    roles: shed
    privs: ALL
    type: sequence


## used by: galaxyproject.nginx
nginx_configs:
  - testtoolshed


## used by: galaxyproject.galaxy_toolshed
galaxy_toolshed_venv_dir: "{{ galaxy_toolshed_root }}/venv"
galaxy_toolshed_config_dir: "{{ galaxy_toolshed_root }}/config"
galaxy_toolshed_config_file: "{{ galaxy_toolshed_config_dir }}/tool_shed.ini"
galaxy_toolshed_mutable_config_dir: "{{ galaxy_toolshed_root }}/var"
galaxy_toolshed_mutable_data_dir: "{{ galaxy_toolshed_root }}/var/data"


## used by: galaxyproject.galaxy
#pip_virtualenv_command: "{{ galaxy_shed_root }}/python/bin/virtualenv"
galaxy_server_dir: "{{ galaxy_toolshed_server_dir }}"
galaxy_venv_dir: "{{ galaxy_toolshed_venv_dir }}"
galaxy_config_file: "{{ galaxy_toolshed_config_file }}" # to fetch the correct eggs

galaxy_errordocs_dest: "{{ nginx_srv }}/{{ galaxy_toolshed_instance_hostname }}/error"
galaxy_errordocs_server_name: "The Test Tool Shed"


# tool_shed.ini contents
galaxy_toolshed_config:
  uwsgi:
    socket: "{{ galaxy_toolshed_mutable_config_dir }}/uwsgi.sock"
    stats: "127.0.0.1:9191"
    processes: 4
    threads: 4
    master: True
    logto: "{{ galaxy_toolshed_log_dir }}/uwsgi.log"
    chmod-socket: 664
    chown-socket: "shed:www-data"
    # this causes an infinite loop waiting for the touch-logreopen file at uwsgi startup, why?
    #"log-reopen": True
    #"touch-logreopen": "{{ galaxy_log_dir }}/uwsgi.logreopen"
    pythonpath: lib
  "app:main":
    # secrets

    id_secret: "{{ galaxy_toolshed_config_id_secret }}"
    admin_users: "{{ galaxy_toolshed_config_admin_users }}"

    # paths

    file_path: "{{ galaxy_toolshed_mutable_data_dir }}/repos"
    new_file_path: "{{ galaxy_toolshed_mutable_data_dir }}/tmp"
    tool_data_path: "{{ galaxy_toolshed_mutable_data_dir }}/tool-data"

    # general stuff

    database_connection: "postgresql:///galaxy_testtoolshed?host=/var/run/postgresql"
    log_level: "DEBUG"
    ga_code: "UA-45719423-8"
    debug: "False"
    use_lint: "False"
    num_tool_test_results_saved: "5"
    support_url: "https://galaxyproject.org/support"
    smtp_server: "smtp.psu.edu"
    email_from: "galaxy-no-reply@toolshed.g2.bx.psu.edu"
    use_new_layout: "True"
    brand: '(sandbox for testing)'
    sentry_dsn: "{{ galaxy_toolshed_config_sentry_dsn }}"
