---

- name: Tool Shed code and dependencies, manage static configs
  hosts: toolshedservers
  remote_user: "{{ toolshed_privileged_user }}"
  roles:
    - role: galaxyproject.galaxy
      galaxy_manage_clone: yes
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
      galaxy_fetch_dependencies: no
      galaxy_manage_errordocs: no
    - role: galaxyproject.galaxy_toolshed
      galaxy_toolshed_manage_static_setup: yes
      galaxy_toolshed_manage_database: no
    - role: galaxyproject.galaxy
      galaxy_manage_clone: no
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
      galaxy_fetch_dependencies: yes
      galaxy_manage_errordocs: yes

- name: Tool Shed database
  hosts: toolshedservers
  remote_user: "{{ toolshed_user }}"
  roles:
    - role: galaxyproject.galaxy_toolshed
      galaxy_toolshed_manage_static_setup: no
      galaxy_toolshed_manage_database: yes
  tasks:
    - name: Set hgweb archive types
      ini_file: dest=~/.hgrc backup=yes section=web option=allow_archive value="bz2, gz, zip"
