---
galaxy_info:
  author: The Galaxy Project
  description: Install and Manage Galaxy (http://galaxyproject.org/) Interactive Environments
  company: The Galaxy Project
  license: AFL v3.0
  min_ansible_version: 1.9
  platforms:
  - name: Fedora
    versions:
    - 21
    - 22
  - name: Ubuntu
    versions:
    - trusty
    - utopic
    - vivid
  - name: Debian
    versions:
    - jessie
  categories:
  - development
  - web
dependencies: []
