---

- name: Install Node and NPM (RedHat)
  yum:
    pkg: "{{ item }}"
  with_items:
    - nodejs
    - npm
  when: ansible_os_family == 'RedHat'

- name: Install Node and NPM (Debian)
  apt:
    pkg: "{{ item }}"
  with_items: 
    - nodejs
    - npm
  when: ansible_os_family == 'Debian'
