---
# tasks file for galaxyproject.interactive_enviroments

- name: Set IE proxy restart handler name
  set_fact:
    interactive_environments_proxy_restart_handler: supervisorctl restart gie_proxy
  when: interactive_environments_supervisor_conf_dir is defined

- name: Set path variables if installing in place
  set_fact:
    interactive_environments_plugin_path: "{{ galaxy_server_dir ~ '/config/plugins/interactive_environments' }}"
    interactive_environments_proxy_path: "{{ galaxy_server_dir ~ 'lib/galaxy/web/proxy/js' }}"
  when: interactive_environments_install_method == 'inplace'

- name: Include tasks for synchronizing IE components
  include: synchronize_components.yml
  when: interactive_environments_install_method == 'copy'

- name: Install proxy dependencies with NPM
  npm:
    path: "{{ interactive_environments_proxy_path }}"

- name: Create IE ini config files
  template:
    src: config.ini.j2
    dest: "{{ interactive_environments_plugins_path }}/{{ item.ie_name }}/config/{{ item.file }}"
    backup: yes
  with_items: "{{ interactive_environments_config_files }}"
  when: "(item.file | splitext)[1] == '.ini'"

- name: Create IE yaml config files
  copy:
    content: "{{ item.contents | to_nice_yaml }}"
    dest: "{{ interactive_environments_plugins_path }}/{{ item.ie_name }}/config/{{ item.file }}"
    backup: yes
  with_items: "{{ interactive_environments_config_files }}"
  when: "(item.file | splitext)[1] in ('.yml', '.yaml')"

- name: Include tasks for supervisor config
  include: supervisor.yml
  when: interactive_environments_supervisor_conf_dir is defined

- name: Include tasks for Docker SSL client
  include: docker_ssl.yml
  when: interactive_environments_ssl is defined

- name: Include tasks for nginx config
  include: webserver_conf.yml
  vars:
    interactive_environments_web_conf_dir: "{{ interactive_environments_nginx_conf_dir }}"
    interactive_environments_web_conf_templates: "{{ interactive_environments_nginx_conf_templates }}"
  when: interactive_environments_nginx_conf_dir is defined

- name: Include tasks for Apache config
  include: webserver_conf.yml
  vars:
    interactive_environments_web_conf_dir: "{{ interactive_environments_apache_conf_dir }}"
    interactive_environments_web_conf_templates: "{{ interactive_environments_apache_conf_templates }}"
  when: interactive_environments_apache_conf_dir is defined
