---

- name: Synchronize IE plugins
  synchronize:
    archive: true
    delete: true
    rsync_opts:
      - "--exclude={{ item }}/config/*.ini"
      - "--exclude={{ item }}/config/*.yml"
    dest: "{{ interactive_environments_plugins_path }}"
    src: "{{ galaxy_server_dir }}/config/plugins/interactive_environments/{{ item }}"
  with_items: "{{ interactive_environments_enabled }}"
  delegate_to: "{{ inventory_hostname }}"

- name: Synchronize IE proxy
  synchronize:
    archive: true
    delete: true
    rsync_opts:
      - "--exclude=node_modules"
    dest: "{{ interactive_environments_proxy_path }}"
    src: "{{ galaxy_server_dir }}/lib/galaxy/web/proxy/js/"
  delegate_to: "{{ inventory_hostname }}"
