---

- name: Create web server config dir if needed and possible
  file:
    dest: "{{ interactive_environments_web_conf_dir }}"
    state: directory

- name: Create IE-specific web server config snippet for IE proxy
  template:
    src: "{{ interactive_environments_web_conf_templates[item] }}.j2"
    dest: "{{ interactive_environments_web_conf_dir }}/{{ interactive_environments_web_conf_templates[item] }}"
  with_items: "{{ interactive_environments_enabled }}"
  when: item in interactive_environments_web_conf_templates

- name: Create generic web server config snippet for IE proxy (nginx)
  template:
    src: "generic_nginx.conf.j2"
    dest: "{{ interactive_environments_nginx_conf_dir }}/generic_nginx.conf"
  when: interactive_environments_nginx_conf_dir is defined

- name: Create generic web server config snippet for IE proxy (Apache)
  template:
    src: "generic_apache.conf.j2"
    dest: "{{ interactive_environments_apache_conf_dir }}/generic_apache.conf"
  when: interactive_environments_apache_conf_dir is defined
