---
# defaults file for galaxyproject.galaxy

# TODO: Magical restarters depending on how you're running Galaxy.
- name: restart galaxy
  debug:
    msg: "RESTARTER NOT IMPLEMENTED - Please restart Galaxy manually"

- name: email administrator with commit id
  mail:
    from: "{{ galaxy_admin_email_from | default( 'root' ) }}"
    to: "{{ galaxy_admin_email_to }}"
    subject: "Galaxy instance {{ galaxy_instance_hostname | default( inventory_hostname ) }} is at commit {{ galaxy_commit_id }}"
    body: " "
  when: galaxy_admin_email_to is defined
